spring.application.name=Local-LLM-Assistant

server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/local_llm_assistant
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.openai.base-url=http://127.0.0.1:8080
spring.ai.openai.api-key=dummy

spring.ai.openai.chat.options.model=Qwen/Qwen2.5-3B-Instruct-GGUF:Q4_K_M
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.max-tokens=150

spring.ai.openai.timeout=300s
spring.ai.openai.max-retries=0